spring:
    application:
        name: spring-cloud-ui
    thymeleaf:
        mode: LEGACYHTML5
        cache: false

server:
    port: 8766
    
eureka:
    instance:
        statusPageUrlPath: ${management.context-path}/info
        healthCheckUrlPath: ${management.context-path}/health
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/